//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct CommandList {


        public struct Favourites {

            /// Base translation: No favourites yet!  Tap the ♡ button to favourite a command.
            public static var None : String = NSLocalizedString("COMMAND_LIST.FAVOURITES.NONE", tableName: nil, bundle: Bundle.main, value: "", comment: "")

        }

        public struct DataSources {

            /// Base translation: Favourites
            public static var Favourites : String = NSLocalizedString("COMMAND_LIST.DATA_SOURCES.FAVOURITES", tableName: nil, bundle: Bundle.main, value: "", comment: "")

        }
    }
}