# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier "uk.co.greenlightapps.tldr-viewer"
overwrite_screenshots true
